name: CI

on:
  schedule:
    # once a month
    - cron: '0 0 1 * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: 'PHP: ${{ matrix.php }}; Laravel: ${{ matrix.laravel }}; PHPUnit: ${{ matrix.phpunit }}; Dependecies: ${{ matrix.dependency-version }}'
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
        laravel: ['~5.6.0', '~5.7.0', '~5.8.0', '^6.0', '^7.0']
        phpunit: ['^7.0', '^8.0', '^9.0']
        dependency-version: ['prefer-lowest', 'prefer-stable']
        exclude:
            - laravel: '^6.0'
              php: '7.1'
            - laravel: '^7.0'
              php: '7.1'
            - phpunit: '^8.0'
              php: '7.1'
            - phpunit: '^9.0'
              php: '7.1'
            - phpunit: '^9.0'
              php: '7.2'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.dependency-version }}-laravel-${{ matrix.laravel }}-phpunit-${{ matrix.phpunit }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-v2

    - name: Install dependencies
      run: |
          composer remove infection/infection --dev --no-update --no-interaction --verbose
          composer require 'illuminate/config:${{ matrix.laravel }}' 'illuminate/container:${{ matrix.laravel }}' 'illuminate/support:${{ matrix.laravel }}' 'phpunit/phpunit:${{ matrix.phpunit }}' --no-update --no-interaction --verbose
          composer update --${{ matrix.dependency-version }} --no-suggest --no-interaction --verbose

    - name: Check platform requirements
      run: composer check-platform-reqs --verbose

    - name: Run tests
      run: ./vendor/bin/phpunit --debug --verbose
